services:
  - type: web
    name: futuristic-search
    env: node
    buildCommand: mvn clean package
    startCommand: java -jar target/dependency/webapp-runner.jar --port $PORT target/*.war
    envVars:
      - key: JAVA_VERSION
        value: 8 